### ISSUE TITLE
Returns nan when lat/lons are very close to each other but aren't the same

### ISSUE THREAD

**Issue by eclark887** [doublemap/cHaversine#2]
`print(haversine((39.8862855,-86.0395778),(39.8862855,-86.0395777))
nan
print(haversine((39.8862855,-86.0395777),(39.8862855,-86.0395777)))
0`

**Comment by erjiang** [comment]
This should be fixed in v0.3.0 which changed the calculation to use a different method that is better conditioned (i.e. less susceptibility to floating-point precision).
